config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client, optional: true

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :set_clients, only: %i[ new edit create destroy update]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_clients
      @clients = Client.all.pluck :name, :id
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<!-- app/views/clients/_client.html.erb -->
<tr id="<%= dom_id client %>">
  <th scope="row"><%= client.id %></th>
  <td><%= client.name %></td>
  <td><%= client.age %></td>
  <td><%= client.movies.last %></td>
  <td><%= link_to "Show", client, class: "btn btn-info btn-sm" %></td>
  <td><%= link_to "Edit", edit_client_path(client), class: "btn btn-warning btn-sm" %></td>
  <td>
    <%= button_to "Destroy", client, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
  </td>
</tr>

app/views/clients/_form.html.erb
<!-- app/views/clients/_form.html.erb -->
<div class="container">
  <h1 class="my-4"><%= client.new_record? ? "Agregar Cliente" : "Editar Cliente" %></h1>

  <%= form_with(model: client, local: true, class: "form-container") do |form| %>
    <!-- Error Messages -->
    <% if client.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Oops! Hubo algunos errores:</h4>
        <ul class="mb-0">
          <% client.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Form Fields -->
    <div class="card">
      <div class="card-body">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Ingrese el nombre del cliente" %>

        <div class="mb-3 mt-3">
          <%= form.label :age, class: "form-label" %>
          <%= form.text_field :age, class: "form-control", placeholder: "Ingrese la edad del cliente" %>
        </div>

        <div class="d-grid gap-2 mt-4">
          <%= form.submit class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<!-- app/views/clients/index.html.erb -->
<div class="container mt-4">
  <%= link_to "New Client", new_client_path, class: "btn btn-success mb-3" %>
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Last Movie</th>
        <th scope="col" colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @clients.any? %>
        <%= render partial: "client", collection: @clients %>
      <% else %>
        <tr>
          <td colspan="7" class="text-center">No clients found</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clients/new.html.erb
<h1>Menu para crear clientes</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Block Busterv2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<!-- app/views/movies/_form.html.erb -->
<div class="container">
  <h1 class="my-4"><%= movie.new_record? ? "Agregar Película" : "Editar Película" %></h1>

  <%= form_with(model: movie, local: true, class: "form-container") do |form| %>
    <!-- Error Messages -->
    <% if movie.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Oops! Hubo algunos errores:</h4>
        <ul class="mb-0">
          <% movie.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Form Fields -->
    <div class="card">
      <div class="card-body">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Ingrese el nombre de la película" %>

        <div class="mb-3 mt-3">
          <%= form.label :client_id, class: "form-label" %>
          <%= form.select :client_id, options_for_select(@clients), { include_blank: "Seleccione un cliente" }, class: "form-select" %>
        </div>

        <div class="d-grid gap-2 mt-4">
          <%= form.submit class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/_movie.html.erb
<!-- app/views/movies/_movie.html.erb -->
<div class="col-md-4 col-lg-3 py-2">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= movie.name %></h5>
      <%= link_to "Show this movie", movie, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<!-- app/views/movies/index.html.erb -->
<p class="text-success"><%= notice %></p>

<div class="container">
  <h1 class="my-4">Peliculas</h1>
  <%= link_to "Agregar Pelicula", new_movie_path, class: "btn btn-success mb-3" %>
  
  <div class="row">
    <% @movies.each do |movie| %>
      <%= render partial: "movie", locals: { movie: movie } %>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<h1>Menu para agregar peliculas</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'BlockBuster', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Clients', clients_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Movies', movies_path, class: 'nav-link' %>
        </li>
    </div>
  </div>
</nav>